name: dotnet Build

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10.0]
        steps:

        - uses: actions/checkout@main
        - uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '7.0.100'
